version: "3"

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -v ./...

  run:
    cmds:
      - docker-compose up --build -d

  stop:
    cmds:
      - docker-compose down

  integration-test:
    cmds:
      - docker-compose up --d db
      - go test -tags=integration -v ./...
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_TABLE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      SSL_MODE: disable